In [53]:
import numpy as profsexy #cambio de nombre de numpy

class Formulas: #Creamos clase madre para resolucion de triangulo

    def __init__(self): #inicializamos la clase
        pass

    def area_triangulo(self, lado):
        return (profsexy.sqrt(3) / 4) * lado**2

    def perimetro_triangulo(self, lado):
        return 3 * lado

class MateAvanzadas(Formulas): #Crear clase Heredada

    def __init__(self, lista_numeros):
        super().__init__() #Creamos una super clase.
        if len(lista_numeros) != 16:
            raise ValueError("La lista debe contener exactamente 16 números.") #la lista debe tener exactamente 16 numeros si no no sirve.
        self.matriz = profsexy.array(lista_numeros).reshape(4, 4) #ponemos los numeros en 4x4

    def determinante(self): #funcion que resuelve determinantes
        return profsexy.linalg.det(self.matriz)

    def transpuesta(self): #funcion de transpuestas
        return self.matriz.T

        # Generamos una lista de 16 números aleatorio
lista_numeros = ([i for i in  profsexy.random.randint(1,100, 16)])

# área de un triángulo equilátero de lado 5
print("Área del triángulo:", mate.area_triangulo(5))

# perímetro de un triángulo equilátero de lado 5
print("Perímetro del triángulo:", mate.perimetro_triangulo(5))

# determinante de la matriz 4x4
print("Determinante de la matriz:", mate.determinante())

# transpuesta de la matriz 4x4
print("Transpuesta de la matriz:", mate.transpuesta())



Área del triángulo: 10.825317547305483
Perímetro del triángulo: 15
Determinante de la matriz: 6707475.999999998
Transpuesta de la matriz: [[94 55 42 47]
 [40 65 81 87]
 [90 59 18 24]
 [42 20 59  6]]


In [ ]:
#No se bien por que sirve el mate.area_triangulo etc pero sirve y eso a mi me sirve.

In [43]:
(profsexy.array([i for i in  profsexy.random.randint(1,100, 16)]).reshape(4,4))

array([[76, 87, 90, 38],
       [39, 74, 15, 76],
       [43, 30, 86,  2],
       [32, 61,  7, 97]])